version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tasks-manager-db
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tasks-manager-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: 9QMlRe73LGe0I+Fvv5jJGsd2yhgK5/GvGkN2fpoahmc=
      JWT_EXPIRATION_MINUTES: 30
      USER_ASSIGNED_TASKS_LIMIT: 5
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tasksdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass

volumes:
  postgres_data:
